name: Build fm-card-mod
on: [ push, pull_request ]
permissions:
  contents: write

jobs:
  build-windows:
    name: Build on Windows
    runs-on: windows-2022

    steps:
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Fetch repo contents
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Rust project
        run: cargo build --release

      - name: Build and package mkpsxiso
        run: |
          cmake --preset ci -S mkpsxiso -G "Visual Studio 17 2022"
          cmake --build build --config Release -t package

      - name: Move artifacts for packaging
        run: |
          mkdir -p bin
          mv build/Release/dumpsxiso.exe bin/
          mv build/Release/mkpsxiso.exe bin/
          mv target/release/fm-card-mod.exe ./

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fm-card-mod-windows
          path: |
            bin/
            patches/
            fm-card-mod.exe
            execute.bat

  build-linux:
    name: Build on Linux
    runs-on: ubuntu-latest

    steps:
      - name: Install prerequisites
        run: |
          sudo apt-get update -y
          sudo apt-get install -y --no-install-recommends build-essential ninja-build

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Fetch repo contents
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Rust project
        run: cargo build --release

      - name: Build and package mkpsxiso
        run: |
          cmake --preset ci -S mkpsxiso
          cmake --build build -t package

      - name: Move artifacts for packaging
        run: |
          mkdir -p bin
          mv build/dumpsxiso bin/
          mv build/mkpsxiso bin/
          mv target/release/fm-card-mod ./

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fm-card-mod-linux
          path: |
            bin/
            patches/
            fm-card-mod

  build-macos:
    name: Build on macOS
    runs-on: macos-latest

    steps:
      - name: Install prerequisites
        run: |
          brew install ninja

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Fetch repo contents
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build Rust project
        run: cargo build --release

      - name: Build and package mkpsxiso
        run: |
          cmake --preset ci -S mkpsxiso
          cmake --build build -t package

      - name: Move artifacts for packaging
        run: |
          mkdir -p bin
          mv build/dumpsxiso bin/
          mv build/mkpsxiso bin/
          mv target/release/fm-card-mod ./

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fm-card-mod-macos
          path: |
            bin/
            patches/
            fm-card-mod

  # This job takes care of creating a new release and uploading the build
  # artifacts if the last commit is associated with a tag.
  create-release:
    name: Create release
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux, build-macos]

    steps:
      - name: Fetch build artifacts
        if: ${{ github.ref_type == 'tag' }}
        uses: actions/download-artifact@v3
        with:
          path: .

      - name: Zip artifacts
        if: ${{ github.ref_type == 'tag' }}
        run: |
          zip -r fm-card-mod-windows.zip fm-card-mod-windows
          zip -r fm-card-mod-linux.zip fm-card-mod-linux
          zip -r fm-card-mod-macos.zip fm-card-mod-macos

      - name: Publish release
        if: ${{ github.ref_type == 'tag' }}
        uses: softprops/action-gh-release@v1
        with:
          fail_on_unmatched_files: true
          # generate_release_notes: true
          files: |
            fm-card-mod-windows.zip
            fm-card-mod-linux.zip
            fm-card-mod-macos.zip
